### ISSUE TITLE
Not an error =)

### ISSUE THREAD

**Issue by prostokorol** [joeisapro/MonoTouch.Fabric#1]
Hi! Can you show an example of integration Crashlytics in latest Xamarin Studio? I have already created an empty XCode project and made all steps of registration in Fabric. But now I can't understand how start Crashlyticks in AppDelegate.cs

Thank you in advance

**Comment by joeisapro** [comment]
Here's how I do it.

Add the following code to the beginning of FinishedLaunching() - I have an ifdef block to make sure it doesn't get executed on simulator builds:

```
        Setup.EnableCrashReporting(() =>
            {
                Crashlytics.SharedInstance.DebugMode = true;
                Crashlytics.StartWithAPIKey("replace_with_your_crashlytics_api_key");

                AppDomain.CurrentDomain.UnhandledException += (sender, e) =>
                {
                    Setup.CaptureManagedInfo(e.ExceptionObject);
                    Setup.CaptureStackFrames(e.ExceptionObject);
                    Setup.ThrowExceptionAsNative(e.ExceptionObject);
                };

                TaskScheduler.UnobservedTaskException += (sender, e) =>
                {
                    Setup.CaptureManagedInfo(e.Exception);
                    Setup.CaptureStackFrames(e.Exception);
                    Setup.ThrowExceptionAsNative(e.Exception);
                };
            }, Path.GetFileNameWithoutExtension(typeof(AppDelegate).Module.Name));
```

The source code for 'Setup' is available here: https://gist.github.com/joeisapro/829665aa232029b48e16   .  It's based on HockeyApp setup code.

Once this is done, you have to make changes to Xamarin Studio to upload your dSyms automatically.  Refer to this post on the Xamarin forums: https://forums.xamarin.com/discussion/comment/132204/#Comment_132204

Hope this helps.  Let me know how you make out!

**Comment by prostokorol** [comment]
Thanks for your response. I integrated your code and all looks fine, but I'm a little confused in settings to upload dSyms      ¯_(ツ)_/¯  I'll try correctly configure unloading again on this weekend
