### ISSUE TITLE
Crashlytics logs about other crash handlers

### ISSUE THREAD

**Issue by tomhamming** [joeisapro/MonoTouch.Fabric#2]
I've set this library up with my app as described, and Crashlytics appears to be starting up. I triggered a crash, the Crashlytics website complained about missing a dSYM, I uploaded the missing dSYM, and I'm not seeing crashes show up. Also, I'm seeing these messages at app startup:

```
[Crashlytics:Crash] Warning: NSUncaughtExceptionHandler is '_ZL17exception_handlerP11NSException' in '/var/mobile/Containers/Bundle/Application/1B4EAC50-64E9-4D15-A2EC-EA1C3E2512F1/BiblePlusiOS.app/BiblePlusiOS'
[Crashlytics] The signal SIGABRT has a non-Crashlytics handler (sigabrt_signal_handler).  This will interfer with reporting.
[Crashlytics] The signal SIGBUS has a non-Crashlytics handler (mono_sigsegv_signal_handler).  This will interfer with reporting.
[Crashlytics] The signal SIGFPE has a non-Crashlytics handler (mono_sigfpe_signal_handler).  This will interfer with reporting.
[Crashlytics] The signal SIGILL has a non-Crashlytics handler (mono_sigill_signal_handler).  This will interfer with reporting.
[Crashlytics] The signal SIGSEGV has a non-Crashlytics handler (mono_sigsegv_signal_handler).  This will interfer with reporting.
[Crashlytics] The signal SIGSYS has a non-Crashlytics handler ((null)).  This will interfer with reporting.
[Crashlytics] The signal SIGTRAP has a non-Crashlytics handler ((null)).  This will interfer with reporting.
```

Are these messages expected? If not and if they're a problem, how might I fix the issue?

**Comment by joeisapro** [comment]
Ideally, dSYM files should be uploaded to Fabric as part of the build process to avoid issues such as these.  Crash reports received by Fabric before it has processed the dSYM file may appear in a few days, or never.  New crashes should start showing up now that you've manually uploaded the dSYM file.

I'm working on a Xamarin Studio add-in that will allow you to onboard your kits, without having to use a proxy Xcode project or the Fabric plugin.  The add-in will also automatically upload your dSYMs during the build process.  It is currently feature complete, but still a little rough around the edges.  It might be available as early as next week.

**Comment by joeisapro** [comment]
Oh, and those messages are expected and totally normal.  Mono also has to be able to handle those signals, on top of Crashlytics.

**Comment by tomhamming** [comment]
:+1: I am very much looking forward to the add-in.
