### ISSUE TITLE
Problem trying to add library

### ISSUE THREAD

**Issue by homerokzam** [joeisapro/MonoTouch.Fabric#7]
Do you know how to solve the problem below?

Could not install package 'MonoTouch.Fabric 1.2.8.1'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile259', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

Thanks,
Homero

**Comment by joeisapro** [comment]
This library is for Xamarin.iOS only, not PCL.

**Comment by homerokzam** [comment]
Holy shit, that's right. Excuse me!

Thanks,
Homero
